export const langPropsArray = [
  {name: 'Abkhazian', abbreviation: 'ab'},
  {name: 'Afar', abbreviation: 'aa'},
  {name: 'Afrikaans', abbreviation: 'af'},
  {name: 'Albanian', abbreviation: 'sq'},
  {name: 'Amharic', abbreviation: 'am'},
  {name: 'Arabic', abbreviation: 'ar', isRtl: true},
  {name: 'Aragonese', abbreviation: 'an'},
  {name: 'Armenian', abbreviation: 'hy'},
  {name: 'Assamese', abbreviation: 'as'},
  {name: 'Avestan', abbreviation: 'ae'},
  {name: 'Aymara', abbreviation: 'ay'},
  {name: 'Azerbaijani', abbreviation: 'az'},
  {name: 'Bashkir', abbreviation: 'ba'},
  {name: 'Basque', abbreviation: 'eu'},
  {name: 'Belarusian', abbreviation: 'be'},
  {name: 'Bengali', abbreviation: 'bn'},
  {name: 'Bihari', abbreviation: 'bh'},
  {name: 'Bislama', abbreviation: 'bi'},
  {name: 'Bosnian', abbreviation: 'bs'},
  {name: 'Breton', abbreviation: 'br'},
  {name: 'Bulgarian', abbreviation: 'bg'},
  {name: 'Burmese', abbreviation: 'my'},
  {name: 'Catalan', abbreviation: 'ca'},
  {name: 'Chamorro', abbreviation: 'ch'},
  {name: 'Chechen', abbreviation: 'ce'},
  {name: 'Chinese', abbreviation: 'zh'},
  {name: 'Slavonic', abbreviation: 'cu'},
  {name: 'Chuvash', abbreviation: 'cv'},
  {name: 'Cornish', abbreviation: 'kw'},
  {name: 'Corsican', abbreviation: 'co'},
  {name: 'Croatian', abbreviation: 'hr'},
  {name: 'Czech', abbreviation: 'cs'},
  {name: 'Danish', abbreviation: 'da'},
  {name: 'Divehi', abbreviation: 'dv'},
  {name: 'Dutch', abbreviation: 'nl'},
  {name: 'Dzongkha', abbreviation: 'dz'},
  {name: 'English', abbreviation: 'en'},
  {name: 'Esperanto', abbreviation: 'eo'},
  {name: 'Estonian', abbreviation: 'et'},
  {name: 'Faroese', abbreviation: 'fo'},
  {name: 'Fijian', abbreviation: 'fj'},
  {name: 'Finnish', abbreviation: 'fi'},
  {name: 'French', abbreviation: 'fr'},
  {name: 'Gaelic; Scottish Gaelic', abbreviation: 'gd'},
  {name: 'Galician', abbreviation: 'gl'},
  {name: 'Georgian', abbreviation: 'ka'},
  {name: 'German', abbreviation: 'de'},
  {name: 'Greek, Modern (1453-)', abbreviation: 'el'},
  {name: 'Guarani', abbreviation: 'gn'},
  {name: 'Gujarati', abbreviation: 'gu'},
  {name: 'Haitian; Haitian Creole', abbreviation: 'ht'},
  {name: 'Hausa', abbreviation: 'ha'},
  {name: 'Hebrew', abbreviation: 'he', isRtl: true},
  {name: 'Herero', abbreviation: 'hz'},
  {name: 'Hindi', abbreviation: 'hi'},
  {name: 'Hiri Motu', abbreviation: 'ho'},
  {name: 'Hungarian', abbreviation: 'hu'},
  {name: 'Icelandic', abbreviation: 'is'},
  {name: 'Ido', abbreviation: 'io'},
  {name: 'Indonesian', abbreviation: 'id'},
  {name: 'Interlingua (International Auxiliary Language Association)', abbreviation: 'ia'},
  {name: 'Interlingue', abbreviation: 'ie'},
  {name: 'Inuktitut', abbreviation: 'iu'},
  {name: 'Inupiaq', abbreviation: 'ik'},
  {name: 'Irish', abbreviation: 'ga'},
  {name: 'Italian', abbreviation: 'it'},
  {name: 'Japanese', abbreviation: 'ja'},
  {name: 'Javanese', abbreviation: 'jv'},
  {name: 'Kalaallisut', abbreviation: 'kl'},
  {name: 'Kannada', abbreviation: 'kn'},
  {name: 'Kashmiri', abbreviation: 'ks'},
  {name: 'Kazakh', abbreviation: 'kk'},
  {name: 'Khmer', abbreviation: 'km'},
  {name: 'Kikuyu; Gikuyu', abbreviation: 'ki'},
  {name: 'Kinyarwanda', abbreviation: 'rw'},
  {name: 'Kirghiz', abbreviation: 'ky'},
  {name: 'Komi', abbreviation: 'kv'},
  {name: 'Korean', abbreviation: 'ko'},
  {name: 'Kuanyama', abbreviation: 'kj'},
  {name: 'Kurdish', abbreviation: 'ku', isRtl: true},
  {name: 'Lao', abbreviation: 'lo'},
  {name: 'Latin', abbreviation: 'la'},
  {name: 'Latvian', abbreviation: 'lv'},
  {name: 'Limburgan; Limburgish', abbreviation: 'li'},
  {name: 'Lingala', abbreviation: 'ln'},
  {name: 'Lithuanian', abbreviation: 'lt'},
  {name: 'Luxembourgish', abbreviation: 'lb'},
  {name: 'Macedonian', abbreviation: 'mk'},
  {name: 'Malagasy', abbreviation: 'mg'},
  {name: 'Malay', abbreviation: 'ms'},
  {name: 'Malayalam', abbreviation: 'ml'},
  {name: 'Maltese', abbreviation: 'mt'},
  {name: 'Manx', abbreviation: 'gv'},
  {name: 'Maori', abbreviation: 'mi'},
  {name: 'Marathi', abbreviation: 'mr'},
  {name: 'Marshallese', abbreviation: 'mh'},
  {name: 'Moldavian', abbreviation: 'mo'},
  {name: 'Mongolian', abbreviation: 'mn'},
  {name: 'Nauru', abbreviation: 'na'},
  {name: 'Navaho, Navajo', abbreviation: 'nv'},
  {name: 'Ndebele, North', abbreviation: 'nd'},
  {name: 'Ndebele, South', abbreviation: 'nr'},
  {name: 'Ndonga', abbreviation: 'ng'},
  {name: 'Nepali', abbreviation: 'ne'},
  {name: 'Northern Sami', abbreviation: 'se'},
  {name: 'Norwegian', abbreviation: 'no'},
  {name: 'Norwegian Bokmal', abbreviation: 'nb'},
  {name: 'Norwegian Nynorsk', abbreviation: 'nn'},
  {name: 'Nyanja', abbreviation: 'ny'},
  {name: 'Occitan (post 1500); Provencal', abbreviation: 'oc'},
  {name: 'Oriya', abbreviation: 'or'},
  {name: 'Oromo', abbreviation: 'om'},
  {name: 'Ossetian; Ossetic', abbreviation: 'os'},
  {name: 'Pali', abbreviation: 'pi'},
  {name: 'Panjabi', abbreviation: 'pa'},
  {name: 'Persian', abbreviation: 'fa', isRtl: true},
  {name: 'Polish', abbreviation: 'pl'},
  {name: 'Portuguese', abbreviation: 'pt'},
  {name: 'Pushto', abbreviation: 'ps'},
  {name: 'Quechua', abbreviation: 'qu'},
  {name: 'Raeto-Romance', abbreviation: 'rm'},
  {name: 'Romanian', abbreviation: 'ro'},
  {name: 'Rundi', abbreviation: 'rn'},
  {name: 'Russian', abbreviation: 'ru'},
  {name: 'Samoan', abbreviation: 'sm'},
  {name: 'Sango', abbreviation: 'sg'},
  {name: 'Sanskrit', abbreviation: 'sa'},
  {name: 'Sardinian', abbreviation: 'sc'},
  {name: 'Serbian', abbreviation: 'sr'},
  {name: 'Shona', abbreviation: 'sn'},
  {name: 'Sichuan Yi', abbreviation: 'ii'},
  {name: 'Sindhi', abbreviation: 'sd'},
  {name: 'Sinhala; Sinhalese', abbreviation: 'si'},
  {name: 'Slovak', abbreviation: 'sk'},
  {name: 'Slovenian', abbreviation: 'sl'},
  {name: 'Somali', abbreviation: 'so'},
  {name: 'Sotho, Southern', abbreviation: 'st'},
  {name: 'Spanish; Castilian', abbreviation: 'es'},
  {name: 'Sundanese', abbreviation: 'su'},
  {name: 'Swahili', abbreviation: 'sw'},
  {name: 'Swati', abbreviation: 'ss'},
  {name: 'Swedish', abbreviation: 'sv'},
  {name: 'Tagalog', abbreviation: 'tl'},
  {name: 'Tahitian', abbreviation: 'ty'},
  {name: 'Tajik', abbreviation: 'tg'},
  {name: 'Tamil', abbreviation: 'ta'},
  {name: 'Tatar', abbreviation: 'tt'},
  {name: 'Telugu', abbreviation: 'te'},
  {name: 'Thai', abbreviation: 'th'},
  {name: 'Tibetan', abbreviation: 'bo'},
  {name: 'Tigrinya', abbreviation: 'ti'},
  {name: 'Tonga (Tonga Islands)', abbreviation: 'to'},
  {name: 'Tsonga', abbreviation: 'ts'},
  {name: 'Tswana', abbreviation: 'tn'},
  {name: 'Turkish', abbreviation: 'tr'},
  {name: 'Turkmen', abbreviation: 'tk'},
  {name: 'Twi', abbreviation: 'tw'},
  {name: 'Uighur', abbreviation: 'ug'},
  {name: 'Ukrainian', abbreviation: 'uk'},
  {name: 'Urdu', abbreviation: 'ur', isRtl: true},
  {name: 'Uzbek', abbreviation: 'uz'},
  {name: 'Vietnamese', abbreviation: 'vi'},
  {name: 'Volapuk', abbreviation: 'vo'},
  {name: 'Walloon', abbreviation: 'wa'},
  {name: 'Welsh', abbreviation: 'cy'},
  {name: 'Western Frisian', abbreviation: 'fy'},
  {name: 'Wolof', abbreviation: 'wo'},
  {name: 'Xhosa', abbreviation: 'xh'},
  {name: 'Yiddish', abbreviation: 'yi'},
  {name: 'Yoruba', abbreviation: 'yo'},
  {name: 'Zhuang', abbreviation: 'za'},
  {name: 'Zulu', abbreviation: 'zu'},];
