// Taken from https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
// code - is ISO 639-1
// codeB - is ISO 639-2/B
// codeT - is ISO 639-2/T

/* tslint:disable:max-line-length */
// noinspection SpellCheckingInspection
export const langPropsArray = [
 {name: 'Abkhazian', nativeName: 'аҧсуа бызшәа, аҧсшәа' , code: 'ab' , codeT: 'abk', codeB: 'abk', family: 'Northwest Caucasian'},
 {name: 'Afar', nativeName: 'Afaraf' , code: 'aa' , codeT: 'aar', codeB: 'aar', family: 'Afro-Asiatic'},
 {name: 'Afrikaans', nativeName: 'Afrikaans' , code: 'af' , codeT: 'afr', codeB: 'afr', family: 'Indo-European'},
 {name: 'Akan', nativeName: 'Akan' , code: 'ak' , codeT: 'aka', codeB: 'aka', family: 'Niger–Congo'},
 {name: 'Albanian', nativeName: 'Shqip' , code: 'sq' , codeT: 'sqi', codeB: 'alb', family: 'Indo-European'},
 {name: 'Amharic', nativeName: 'አማርኛ' , code: 'am' , codeT: 'amh', codeB: 'amh', family: 'Afro-Asiatic'},
 {name: 'Arabic', nativeName: 'العربية' , code: 'ar' , codeT: 'ara', codeB: 'ara', family: 'Afro-Asiatic', isRtl: true},
 {name: 'Aragonese', nativeName: 'aragonés' , code: 'an' , codeT: 'arg', codeB: 'arg', family: 'Indo-European'},
 {name: 'Armenian', nativeName: 'Հայերեն' , code: 'hy' , codeT: 'hye', codeB: 'arm', family: 'Indo-European'},
 {name: 'Assamese', nativeName: 'অসমীয়া' , code: 'as' , codeT: 'asm', codeB: 'asm', family: 'Indo-European'},
 {name: 'Avaric', nativeName: 'авар мацӀ, магӀарул мацӀ' , code: 'av' , codeT: 'ava', codeB: 'ava', family: 'Northeast Caucasian'},
 {name: 'Avestan', nativeName: 'avesta' , code: 'ae' , codeT: 'ave', codeB: 'ave', family: 'Indo-European'},
 {name: 'Aymara', nativeName: 'aymar aru' , code: 'ay' , codeT: 'aym', codeB: 'aym', family: 'Aymaran'},
 {name: 'Azerbaijani', nativeName: 'azərbaycan dili' , code: 'az' , codeT: 'aze', codeB: 'aze', family: 'Turkic'},
 {name: 'Bambara', nativeName: 'bamanankan' , code: 'bm' , codeT: 'bam', codeB: 'bam', family: 'Niger–Congo'},
 {name: 'Bashkir', nativeName: 'башҡорт теле' , code: 'ba' , codeT: 'bak', codeB: 'bak', family: 'Turkic'},
 {name: 'Basque', nativeName: 'euskara, euskera' , code: 'eu' , codeT: 'eus', codeB: 'baq', family: 'Language isolate'},
 {name: 'Belarusian', nativeName: 'беларуская мова' , code: 'be' , codeT: 'bel', codeB: 'bel', family: 'Indo-European'},
 {name: 'Bengali', nativeName: 'বাংলা' , code: 'bn' , codeT: 'ben', codeB: 'ben', family: 'Indo-European'},
 {name: 'Bihari languages', nativeName: 'भोजपुरी' , code: 'bh' , codeT: 'bih', codeB: 'bih', family: 'Indo-European'},
 {name: 'Bislama', nativeName: 'Bislama' , code: 'bi' , codeT: 'bis', codeB: 'bis', family: 'Creole'},
 {name: 'Bosnian', nativeName: 'bosanski jezik' , code: 'bs' , codeT: 'bos', codeB: 'bos', family: 'Indo-European'},
 {name: 'Breton', nativeName: 'brezhoneg' , code: 'br' , codeT: 'bre', codeB: 'bre', family: 'Indo-European'},
 {name: 'Bulgarian', nativeName: 'български език' , code: 'bg' , codeT: 'bul', codeB: 'bul', family: 'Indo-European'},
 {name: 'Burmese', nativeName: 'ဗမာစာ' , code: 'my' , codeT: 'mya', codeB: 'bur', family: 'Sino-Tibetan'},
 {name: 'Catalan, Valencian', nativeName: 'català, valencià' , code: 'ca' , codeT: 'cat', codeB: 'cat', family: 'Indo-European'},
 {name: 'Chamorro', nativeName: 'Chamoru' , code: 'ch' , codeT: 'cha', codeB: 'cha', family: 'Austronesian'},
 {name: 'Chechen', nativeName: 'нохчийн мотт' , code: 'ce' , codeT: 'che', codeB: 'che', family: 'Northeast Caucasian'},
 {name: 'Chichewa, Chewa, Nyanja', nativeName: 'chiCheŵa, chinyanja' , code: 'ny' , codeT: 'nya', codeB: 'nya', family: 'Niger–Congo'},
 {name: 'Chinese', nativeName: '中文 (Zhōngwén), 汉语, 漢語' , code: 'zh' , codeT: 'zho', codeB: 'chi', family: 'Sino-Tibetan'},
 {name: 'Chuvash', nativeName: 'чӑваш чӗлхи' , code: 'cv' , codeT: 'chv', codeB: 'chv', family: 'Turkic'},
 {name: 'Cornish', nativeName: 'Kernewek' , code: 'kw' , codeT: 'cor', codeB: 'cor', family: 'Indo-European'},
 {name: 'Corsican', nativeName: 'corsu, lingua corsa' , code: 'co' , codeT: 'cos', codeB: 'cos', family: 'Indo-European'},
 {name: 'Cree', nativeName: 'ᓀᐦᐃᔭᐍᐏᐣ' , code: 'cr' , codeT: 'cre', codeB: 'cre', family: 'Algonquian'},
 {name: 'Croatian', nativeName: 'hrvatski jezik' , code: 'hr' , codeT: 'hrv', codeB: 'hrv', family: 'Indo-European'},
 {name: 'Czech', nativeName: 'čeština, český jazyk' , code: 'cs' , codeT: 'ces', codeB: 'cze', family: 'Indo-European'},
 {name: 'Danish', nativeName: 'dansk' , code: 'da' , codeT: 'dan', codeB: 'dan', family: 'Indo-European'},
 {name: 'Divehi, Dhivehi, Maldivian', nativeName: 'ދިވެހި' , code: 'dv' , codeT: 'div', codeB: 'div', family: 'Indo-European'},
 {name: 'Dutch, Flemish', nativeName: 'Nederlands, Vlaams' , code: 'nl' , codeT: 'nld', codeB: 'dut', family: 'Indo-European'},
 {name: 'Dzongkha', nativeName: 'རྫོང་ཁ' , code: 'dz' , codeT: 'dzo', codeB: 'dzo', family: 'Sino-Tibetan'},
 {name: 'English', nativeName: 'English' , code: 'en' , codeT: 'eng', codeB: 'eng', family: 'Indo-European'},
 {name: 'Esperanto', nativeName: 'Esperanto' , code: 'eo' , codeT: 'epo', codeB: 'epo', family: 'Constructed'},
 {name: 'Estonian', nativeName: 'eesti, eesti keel' , code: 'et' , codeT: 'est', codeB: 'est', family: 'Uralic'},
 {name: 'Ewe', nativeName: 'Eʋegbe' , code: 'ee' , codeT: 'ewe', codeB: 'ewe', family: 'Niger–Congo'},
 {name: 'Faroese', nativeName: 'føroyskt' , code: 'fo' , codeT: 'fao', codeB: 'fao', family: 'Indo-European'},
 {name: 'Fijian', nativeName: 'vosa Vakaviti' , code: 'fj' , codeT: 'fij', codeB: 'fij', family: 'Austronesian'},
 {name: 'Finnish', nativeName: 'suomi, suomen kieli' , code: 'fi' , codeT: 'fin', codeB: 'fin', family: 'Uralic'},
 {name: 'French', nativeName: 'français, langue française' , code: 'fr' , codeT: 'fra', codeB: 'fre', family: 'Indo-European'},
 {name: 'Fulah', nativeName: 'Fulfulde, Pulaar, Pular' , code: 'ff' , codeT: 'ful', codeB: 'ful', family: 'Niger–Congo'},
 {name: 'Galician', nativeName: 'Galego' , code: 'gl' , codeT: 'glg', codeB: 'glg', family: 'Indo-European'},
 {name: 'Georgian', nativeName: 'ქართული' , code: 'ka' , codeT: 'kat', codeB: 'geo', family: 'Kartvelian'},
 {name: 'German', nativeName: 'Deutsch' , code: 'de' , codeT: 'deu', codeB: 'ger', family: 'Indo-European'},
 {name: 'Greek, Modern (1453-)', nativeName: 'ελληνικά' , code: 'el' , codeT: 'ell', codeB: 'gre', family: 'Indo-European'},
 {name: 'Guarani', nativeName: 'Avañe\'ẽ' , code: 'gn' , codeT: 'grn', codeB: 'grn', family: 'Tupian'},
 {name: 'Gujarati', nativeName: 'ગુજરાતી' , code: 'gu' , codeT: 'guj', codeB: 'guj', family: 'Indo-European'},
 {name: 'Haitian, Haitian Creole', nativeName: 'Kreyòl ayisyen' , code: 'ht' , codeT: 'hat', codeB: 'hat', family: 'Creole'},
 {name: 'Hausa', nativeName: '(Hausa) هَوُسَ' , code: 'ha' , codeT: 'hau', codeB: 'hau', family: 'Afro-Asiatic'},
 {name: 'Hebrew', nativeName: 'עברית' , code: 'he' , codeT: 'heb', codeB: 'heb', family: 'Afro-Asiatic', isRtl: true},
 {name: 'Herero', nativeName: 'Otjiherero' , code: 'hz' , codeT: 'her', codeB: 'her', family: 'Niger–Congo'},
 {name: 'Hindi', nativeName: 'हिन्दी, हिंदी' , code: 'hi' , codeT: 'hin', codeB: 'hin', family: 'Indo-European'},
 {name: 'Hiri Motu', nativeName: 'Hiri Motu' , code: 'ho' , codeT: 'hmo', codeB: 'hmo', family: 'Austronesian'},
 {name: 'Hungarian', nativeName: 'magyar' , code: 'hu' , codeT: 'hun', codeB: 'hun', family: 'Uralic'},
 {name: 'Interlingua (International Auxiliary Language Association)', nativeName: 'Interlingua' , code: 'ia' , codeT: 'ina', codeB: 'ina', family: 'Constructed'},
 {name: 'Indonesian', nativeName: 'Bahasa Indonesia' , code: 'id' , codeT: 'ind', codeB: 'ind', family: 'Austronesian'},
 {name: 'Interlingue, Occidental', nativeName: '(originally:) Occidental, (after WWII:) Interlingue' , code: 'ie' , codeT: 'ile', codeB: 'ile', family: 'Constructed'},
 {name: 'Irish', nativeName: 'Gaeilge' , code: 'ga' , codeT: 'gle', codeB: 'gle', family: 'Indo-European'},
 {name: 'Igbo', nativeName: 'Asụsụ Igbo' , code: 'ig' , codeT: 'ibo', codeB: 'ibo', family: 'Niger–Congo'},
 {name: 'Inupiaq', nativeName: 'Iñupiaq, Iñupiatun' , code: 'ik' , codeT: 'ipk', codeB: 'ipk', family: 'Eskimo–Aleut'},
 {name: 'Ido', nativeName: 'Ido' , code: 'io' , codeT: 'ido', codeB: 'ido', family: 'Constructed'},
 {name: 'Icelandic', nativeName: 'Íslenska' , code: 'is' , codeT: 'isl', codeB: 'ice', family: 'Indo-European'},
 {name: 'Italian', nativeName: 'Italiano' , code: 'it' , codeT: 'ita', codeB: 'ita', family: 'Indo-European'},
 {name: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ' , code: 'iu' , codeT: 'iku', codeB: 'iku', family: 'Eskimo–Aleut'},
 {name: 'Japanese', nativeName: '日本語 (にほんご)' , code: 'ja' , codeT: 'jpn', codeB: 'jpn', family: 'Japonic'},
 {name: 'Javanese', nativeName: 'ꦧꦱꦗꦮ, Basa Jawa' , code: 'jv' , codeT: 'jav', codeB: 'jav', family: 'Austronesian'},
 {name: 'Kalaallisut, Greenlandic', nativeName: 'kalaallisut, kalaallit oqaasii' , code: 'kl' , codeT: 'kal', codeB: 'kal', family: 'Eskimo–Aleut'},
 {name: 'Kannada', nativeName: 'ಕನ್ನಡ' , code: 'kn' , codeT: 'kan', codeB: 'kan', family: 'Dravidian'},
 {name: 'Kanuri', nativeName: 'Kanuri' , code: 'kr' , codeT: 'kau', codeB: 'kau', family: 'Nilo-Saharan'},
 {name: 'Kashmiri', nativeName: 'कश्मीरी, كشميري' , code: 'ks' , codeT: 'kas', codeB: 'kas', family: 'Indo-European'},
 {name: 'Kazakh', nativeName: 'қазақ тілі' , code: 'kk' , codeT: 'kaz', codeB: 'kaz', family: 'Turkic'},
 {name: 'Central Khmer', nativeName: 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ' , code: 'km' , codeT: 'khm', codeB: 'khm', family: 'Austroasiatic'},
 {name: 'Kikuyu, Gikuyu', nativeName: 'Gĩkũyũ' , code: 'ki' , codeT: 'kik', codeB: 'kik', family: 'Niger–Congo'},
 {name: 'Kinyarwanda', nativeName: 'Ikinyarwanda' , code: 'rw' , codeT: 'kin', codeB: 'kin', family: 'Niger–Congo'},
 {name: 'Kirghiz, Kyrgyz', nativeName: 'Кыргызча, Кыргыз тили' , code: 'ky' , codeT: 'kir', codeB: 'kir', family: 'Turkic'},
 {name: 'Komi', nativeName: 'коми кыв' , code: 'kv' , codeT: 'kom', codeB: 'kom', family: 'Uralic'},
 {name: 'Kongo', nativeName: 'Kikongo' , code: 'kg' , codeT: 'kon', codeB: 'kon', family: 'Niger–Congo'},
 {name: 'Korean', nativeName: '한국어' , code: 'ko' , codeT: 'kor', codeB: 'kor', family: 'Koreanic'},
 {name: 'Kurdish', nativeName: 'Kurdî, کوردی' , code: 'ku' , codeT: 'kur', codeB: 'kur', family: 'Indo-European', isRtl: true},
 {name: 'Kuanyama, Kwanyama', nativeName: 'Kuanyama' , code: 'kj' , codeT: 'kua', codeB: 'kua', family: 'Niger–Congo'},
 {name: 'Latin', nativeName: 'latine, lingua latina' , code: 'la' , codeT: 'lat', codeB: 'lat', family: 'Indo-European'},
 {name: 'Luxembourgish, Letzeburgesch', nativeName: 'Lëtzebuergesch' , code: 'lb' , codeT: 'ltz', codeB: 'ltz', family: 'Indo-European'},
 {name: 'Ganda', nativeName: 'Luganda' , code: 'lg' , codeT: 'lug', codeB: 'lug', family: 'Niger–Congo'},
 {name: 'Limburgan, Limburger, Limburgish', nativeName: 'Limburgs' , code: 'li' , codeT: 'lim', codeB: 'lim', family: 'Indo-European'},
 {name: 'Lingala', nativeName: 'Lingála' , code: 'ln' , codeT: 'lin', codeB: 'lin', family: 'Niger–Congo'},
 {name: 'Lao', nativeName: 'ພາສາລາວ' , code: 'lo' , codeT: 'lao', codeB: 'lao', family: 'Tai–Kadai'},
 {name: 'Lithuanian', nativeName: 'lietuvių kalba' , code: 'lt' , codeT: 'lit', codeB: 'lit', family: 'Indo-European'},
 {name: 'Luba-Katanga', nativeName: 'Kiluba' , code: 'lu' , codeT: 'lub', codeB: 'lub', family: 'Niger–Congo'},
 {name: 'Latvian', nativeName: 'latviešu valoda' , code: 'lv' , codeT: 'lav', codeB: 'lav', family: 'Indo-European'},
 {name: 'Manx', nativeName: 'Gaelg, Gailck' , code: 'gv' , codeT: 'glv', codeB: 'glv', family: 'Indo-European'},
 {name: 'Macedonian', nativeName: 'македонски јазик' , code: 'mk' , codeT: 'mkd', codeB: 'mac', family: 'Indo-European'},
 {name: 'Malagasy', nativeName: 'fiteny malagasy' , code: 'mg' , codeT: 'mlg', codeB: 'mlg', family: 'Austronesian'},
 {name: 'Malay', nativeName: 'Bahasa Melayu, بهاس ملايو' , code: 'ms' , codeT: 'msa', codeB: 'may', family: 'Austronesian'},
 {name: 'Malayalam', nativeName: 'മലയാളം' , code: 'ml' , codeT: 'mal', codeB: 'mal', family: 'Dravidian'},
 {name: 'Maltese', nativeName: 'Malti' , code: 'mt' , codeT: 'mlt', codeB: 'mlt', family: 'Afro-Asiatic'},
 {name: 'Maori', nativeName: 'te reo Māori' , code: 'mi' , codeT: 'mri', codeB: 'mao', family: 'Austronesian'},
 {name: 'Marathi', nativeName: 'मराठी' , code: 'mr' , codeT: 'mar', codeB: 'mar', family: 'Indo-European'},
 {name: 'Marshallese', nativeName: 'Kajin M̧ajeļ' , code: 'mh' , codeT: 'mah', codeB: 'mah', family: 'Austronesian'},
 {name: 'Mongolian', nativeName: 'Монгол хэл' , code: 'mn' , codeT: 'mon', codeB: 'mon', family: 'Mongolic'},
 {name: 'Nauru', nativeName: 'Dorerin Naoero' , code: 'na' , codeT: 'nau', codeB: 'nau', family: 'Austronesian'},
 {name: 'Navajo, Navaho', nativeName: 'Diné bizaad' , code: 'nv' , codeT: 'nav', codeB: 'nav', family: 'Dené–Yeniseian'},
 {name: 'North Ndebele', nativeName: 'isiNdebele' , code: 'nd' , codeT: 'nde', codeB: 'nde', family: 'Niger–Congo'},
 {name: 'Nepali', nativeName: 'नेपाली' , code: 'ne' , codeT: 'nep', codeB: 'nep', family: 'Indo-European'},
 {name: 'Ndonga', nativeName: 'Owambo' , code: 'ng' , codeT: 'ndo', codeB: 'ndo', family: 'Niger–Congo'},
 {name: 'Norwegian Bokmål', nativeName: 'Norsk Bokmål' , code: 'nb' , codeT: 'nob', codeB: 'nob', family: 'Indo-European'},
 {name: 'Norwegian Nynorsk', nativeName: 'Norsk Nynorsk' , code: 'nn' , codeT: 'nno', codeB: 'nno', family: 'Indo-European'},
 {name: 'Norwegian', nativeName: 'Norsk' , code: 'no' , codeT: 'nor', codeB: 'nor', family: 'Indo-European'},
 {name: 'Sichuan Yi, Nuosu', nativeName: 'ꆈꌠ꒿ Nuosuhxop' , code: 'ii' , codeT: 'iii', codeB: 'iii', family: 'Sino-Tibetan'},
 {name: 'South Ndebele', nativeName: 'isiNdebele' , code: 'nr' , codeT: 'nbl', codeB: 'nbl', family: 'Niger–Congo'},
 {name: 'Occitan', nativeName: 'occitan, lenga d\'òc' , code: 'oc' , codeT: 'oci', codeB: 'oci', family: 'Indo-European'},
 {name: 'Ojibwa', nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' , code: 'oj' , codeT: 'oji', codeB: 'oji', family: 'Algonquian'},
 {name: 'Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic', nativeName: 'ѩзыкъ словѣньскъ' , code: 'cu' , codeT: 'chu', codeB: 'chu', family: 'Indo-European'},
 {name: 'Oromo', nativeName: 'Afaan Oromoo' , code: 'om' , codeT: 'orm', codeB: 'orm', family: 'Afro-Asiatic'},
 {name: 'Oriya', nativeName: 'ଓଡ଼ିଆ' , code: 'or' , codeT: 'ori', codeB: 'ori', family: 'Indo-European'},
 {name: 'Ossetian, Ossetic', nativeName: 'ирон æвзаг' , code: 'os' , codeT: 'oss', codeB: 'oss', family: 'Indo-European'},
 {name: 'Punjabi, Panjabi', nativeName: 'ਪੰਜਾਬੀ, پنجابی' , code: 'pa' , codeT: 'pan', codeB: 'pan', family: 'Indo-European'},
 {name: 'Pali', nativeName: 'पालि, पाळि' , code: 'pi' , codeT: 'pli', codeB: 'pli', family: 'Indo-European'},
 {name: 'Persian', nativeName: 'فارسی' , code: 'fa' , codeT: 'fas', codeB: 'per', family: 'Indo-European', isRtl: true},
 {name: 'Polish', nativeName: 'język polski, polszczyzna' , code: 'pl' , codeT: 'pol', codeB: 'pol', family: 'Indo-European'},
 {name: 'Pashto, Pushto', nativeName: 'پښتو' , code: 'ps' , codeT: 'pus', codeB: 'pus', family: 'Indo-European'},
 {name: 'Portuguese', nativeName: 'Português' , code: 'pt' , codeT: 'por', codeB: 'por', family: 'Indo-European'},
 {name: 'Quechua', nativeName: 'Runa Simi, Kichwa' , code: 'qu' , codeT: 'que', codeB: 'que', family: 'Quechuan'},
 {name: 'Romansh', nativeName: 'Rumantsch Grischun' , code: 'rm' , codeT: 'roh', codeB: 'roh', family: 'Indo-European'},
 {name: 'Rundi', nativeName: 'Ikirundi' , code: 'rn' , codeT: 'run', codeB: 'run', family: 'Niger–Congo'},
 {name: 'Romanian, Moldavian, Moldovan', nativeName: 'Română' , code: 'ro' , codeT: 'ron', codeB: 'rum', family: 'Indo-European'},
 {name: 'Russian', nativeName: 'русский' , code: 'ru' , codeT: 'rus', codeB: 'rus', family: 'Indo-European'},
 {name: 'Sanskrit', nativeName: 'संस्कृतम्' , code: 'sa' , codeT: 'san', codeB: 'san', family: 'Indo-European'},
 {name: 'Sardinian', nativeName: 'sardu' , code: 'sc' , codeT: 'srd', codeB: 'srd', family: 'Indo-European'},
 {name: 'Sindhi', nativeName: 'सिन्धी, سنڌي، سندھی' , code: 'sd' , codeT: 'snd', codeB: 'snd', family: 'Indo-European'},
 {name: 'Northern Sami', nativeName: 'Davvisámegiella' , code: 'se' , codeT: 'sme', codeB: 'sme', family: 'Uralic'},
 {name: 'Samoan', nativeName: 'gagana fa\'a Samoa' , code: 'sm' , codeT: 'smo', codeB: 'smo', family: 'Austronesian'},
 {name: 'Sango', nativeName: 'yângâ tî sängö' , code: 'sg' , codeT: 'sag', codeB: 'sag', family: 'Creole'},
 {name: 'Serbian', nativeName: 'српски језик' , code: 'sr' , codeT: 'srp', codeB: 'srp', family: 'Indo-European'},
 {name: 'Gaelic, Scottish Gaelic', nativeName: 'Gàidhlig' , code: 'gd' , codeT: 'gla', codeB: 'gla', family: 'Indo-European'},
 {name: 'Shona', nativeName: 'chiShona' , code: 'sn' , codeT: 'sna', codeB: 'sna', family: 'Niger–Congo'},
 {name: 'Sinhala, Sinhalese', nativeName: 'සිංහල' , code: 'si' , codeT: 'sin', codeB: 'sin', family: 'Indo-European'},
 {name: 'Slovak', nativeName: 'Slovenčina, Slovenský Jazyk' , code: 'sk' , codeT: 'slk', codeB: 'slo', family: 'Indo-European'},
 {name: 'Slovenian', nativeName: 'Slovenski Jezik, Slovenščina' , code: 'sl' , codeT: 'slv', codeB: 'slv', family: 'Indo-European'},
 {name: 'Somali', nativeName: 'Soomaaliga, af Soomaali' , code: 'so' , codeT: 'som', codeB: 'som', family: 'Afro-Asiatic'},
 {name: 'Southern Sotho', nativeName: 'Sesotho' , code: 'st' , codeT: 'sot', codeB: 'sot', family: 'Niger–Congo'},
 {name: 'Spanish, Castilian', nativeName: 'Español' , code: 'es' , codeT: 'spa', codeB: 'spa', family: 'Indo-European'},
 {name: 'Sundanese', nativeName: 'Basa Sunda' , code: 'su' , codeT: 'sun', codeB: 'sun', family: 'Austronesian'},
 {name: 'Swahili', nativeName: 'Kiswahili' , code: 'sw' , codeT: 'swa', codeB: 'swa', family: 'Niger–Congo'},
 {name: 'Swati', nativeName: 'SiSwati' , code: 'ss' , codeT: 'ssw', codeB: 'ssw', family: 'Niger–Congo'},
 {name: 'Swedish', nativeName: 'Svenska' , code: 'sv' , codeT: 'swe', codeB: 'swe', family: 'Indo-European'},
 {name: 'Tamil', nativeName: 'தமிழ்' , code: 'ta' , codeT: 'tam', codeB: 'tam', family: 'Dravidian'},
 {name: 'Telugu', nativeName: 'తెలుగు' , code: 'te' , codeT: 'tel', codeB: 'tel', family: 'Dravidian'},
 {name: 'Tajik', nativeName: 'тоҷикӣ, toçikī, تاجیکی' , code: 'tg' , codeT: 'tgk', codeB: 'tgk', family: 'Indo-European'},
 {name: 'Thai', nativeName: 'ไทย' , code: 'th' , codeT: 'tha', codeB: 'tha', family: 'Tai–Kadai'},
 {name: 'Tigrinya', nativeName: 'ትግርኛ' , code: 'ti' , codeT: 'tir', codeB: 'tir', family: 'Afro-Asiatic'},
 {name: 'Tibetan', nativeName: 'བོད་ཡིག' , code: 'bo' , codeT: 'bod', codeB: 'tib', family: 'Sino-Tibetan'},
 {name: 'Turkmen', nativeName: 'Türkmen, Түркмен' , code: 'tk' , codeT: 'tuk', codeB: 'tuk', family: 'Turkic'},
 {name: 'Tagalog', nativeName: 'Wikang Tagalog' , code: 'tl' , codeT: 'tgl', codeB: 'tgl', family: 'Austronesian'},
 {name: 'Tswana', nativeName: 'Setswana' , code: 'tn' , codeT: 'tsn', codeB: 'tsn', family: 'Niger–Congo'},
 {name: 'Tonga (Tonga Islands)', nativeName: 'Faka Tonga' , code: 'to' , codeT: 'ton', codeB: 'ton', family: 'Austronesian'},
 {name: 'Turkish', nativeName: 'Türkçe' , code: 'tr' , codeT: 'tur', codeB: 'tur', family: 'Turkic'},
 {name: 'Tsonga', nativeName: 'Xitsonga' , code: 'ts' , codeT: 'tso', codeB: 'tso', family: 'Niger–Congo'},
 {name: 'Tatar', nativeName: 'татар теле, tatar tele' , code: 'tt' , codeT: 'tat', codeB: 'tat', family: 'Turkic'},
 {name: 'Twi', nativeName: 'Twi' , code: 'tw' , codeT: 'twi', codeB: 'twi', family: 'Niger–Congo'},
 {name: 'Tahitian', nativeName: 'Reo Tahiti' , code: 'ty' , codeT: 'tah', codeB: 'tah', family: 'Austronesian'},
 {name: 'Uighur, Uyghur', nativeName: 'ئۇيغۇرچە, Uyghurche' , code: 'ug' , codeT: 'uig', codeB: 'uig', family: 'Turkic'},
 {name: 'Ukrainian', nativeName: 'Українська' , code: 'uk' , codeT: 'ukr', codeB: 'ukr', family: 'Indo-European'},
 {name: 'Urdu', nativeName: 'اردو' , code: 'ur' , codeT: 'urd', codeB: 'urd', family: 'Indo-European', isRtl: true},
 {name: 'Uzbek', nativeName: 'Oʻzbek, Ўзбек, أۇزبېك' , code: 'uz' , codeT: 'uzb', codeB: 'uzb', family: 'Turkic'},
 {name: 'Venda', nativeName: 'Tshivenḓa' , code: 've' , codeT: 'ven', codeB: 'ven', family: 'Niger–Congo'},
 {name: 'Vietnamese', nativeName: 'Tiếng Việt' , code: 'vi' , codeT: 'vie', codeB: 'vie', family: 'Austroasiatic'},
 {name: 'Volapük', nativeName: 'Volapük' , code: 'vo' , codeT: 'vol', codeB: 'vol', family: 'Constructed'},
 {name: 'Walloon', nativeName: 'Walon' , code: 'wa' , codeT: 'wln', codeB: 'wln', family: 'Indo-European'},
 {name: 'Welsh', nativeName: 'Cymraeg' , code: 'cy' , codeT: 'cym', codeB: 'wel', family: 'Indo-European'},
 {name: 'Wolof', nativeName: 'Wollof' , code: 'wo' , codeT: 'wol', codeB: 'wol', family: 'Niger–Congo'},
 {name: 'Western Frisian', nativeName: 'Frysk' , code: 'fy' , codeT: 'fry', codeB: 'fry', family: 'Indo-European'},
 {name: 'Xhosa', nativeName: 'isiXhosa' , code: 'xh' , codeT: 'xho', codeB: 'xho', family: 'Niger–Congo'},
 {name: 'Yiddish', nativeName: 'ייִדיש' , code: 'yi' , codeT: 'yid', codeB: 'yid', family: 'Indo-European'},
 {name: 'Yoruba', nativeName: 'Yorùbá' , code: 'yo' , codeT: 'yor', codeB: 'yor', family: 'Niger–Congo'},
 {name: 'Zhuang, Chuang', nativeName: 'Saɯ cueŋƅ, Saw cuengh' , code: 'za' , codeT: 'zha', codeB: 'zha', family: 'Tai–Kadai'},
];
